<?php

print "<!DOCTYPE html>\n";
print "<html lang=\"en\">\n";
print "<head>\n";
print "    <meta charset=\"UTF-8\">\n";
print "    <title>WeTech | Classes</title>\n";
print "    <link rel=\"stylesheet\" type=\"text/css\" href=\"startup.css\">\n";
print "</head>\n";
print "<body>\n";
print "\n";
print "<div id=\"header\">\n";
print "    <h1>WeTech</h1>\n";
print "    <i>Helping everyone on their journey to digital literacy, one step at a time</i>\n";
print "</div>\n";
print "\n";
print "<ul>\n";
print "    <li><a href=\"startup.html\">Home</a></li>\n";
print "    <li><a href=\"classes.html\">Classes</a></li>\n";
print "    <li><a href=\"timetable.html\">Timetables</a></li>\n";
print "</ul>\n";
print "\n";
print "\n";
print "<h1>Classes</h1>\n";
print "<p>Browse our list of classes below to find which is right for you.</p>\n";
print "\n";
print "<h2>Microsoft Office</h2>\n";
print "<table>\n";
print "    <tr>\n";
print "        <th>Class Topic</th>\n";
print "        <th>Details</th>\n";
print "    </tr>\n";
print "    <tr>\n";
print "        <td>Microsoft Word</td>\n";
print "        <td>Learn the basics of the latest version of Microsoft Word, one of the most popular word processing programs\n";
print "            in the world.\n";
print "        </td>\n";
print "    </tr>\n";
print "    <tr>\n";
print "        <td>Microsoft PowerPoint</td>\n";
print "        <td>Learn the basics of the latest version of Microsoft PowerPoint, a slide show program that allows you to make\n";
print "            professional looking presentations easily.\n";
print "        </td>\n";
print "    </tr>\n";
print "    <tr>\n";
print "        <td>Microsoft Excel</td>\n";
print "        <td>Learn the basics of the latest version of Microsoft Excel, a program that allows you to make spreadsheets\n";
print "            and calculate your data easily.\n";
print "        </td>\n";
print "    </tr>\n";
print "</table>\n";
print "\n";
print "<h2>Google Drive Services</h2>\n";
print "<table>\n";
print "    <tr>\n";
print "        <th>Class Topic</th>\n";
print "        <th>Description</th>\n";
print "    </tr>\n";
print "    <tr>\n";
print "        <td>Google Drive Basics</td>\n";
print "        <td>Learn the basics of Google Drive, a secure cloud storage system that stores your files without taking up\n";
print "            space on your computer.\n";
print "        </td>\n";
print "    </tr>\n";
print "    <tr>\n";
print "        <td>Google Docs</td>\n";
print "        <td>Learn the basics of Google Docs, a word processing system that lives entirely in the cloud and allows\n";
print "            collaboration between users on a single document.\n";
print "        </td>\n";
print "    </tr>\n";
print "    <tr>\n";
print "        <td>Google Slides</td>\n";
print "        <td>Learn the basics of Google Slides, a slide show program that lives entirely in the cloud and allows\n";
print "            collaboration between users on a single slide show.\n";
print "        </td>\n";
print "    </tr>\n";
print "    <tr>\n";
print "        <td>Google Sheets</td>\n";
print "        <td>Learn the basics of Google Sheets, a program that creates spreadsheets that are open to collaboration\n";
print "            between users.\n";
print "        </td>\n";
print "    </tr>\n";
print "</table>\n";
print "\n";
print "<h2>Adobe Suite</h2>\n";
print "<table>\n";
print "    <tr>\n";
print "        <th>Class Topic</th>\n";
print "        <th>Description</th>\n";
print "    </tr>\n";
print "    <tr>\n";
print "        <td>Photoshop</td>\n";
print "        <td>Learn the basics of Adobe Photoshop, the world's most famous image editing program.</td>\n";
print "    </tr>\n";
print "    <tr>\n";
print "        <td>Illustrator</td>\n";
print "        <td>Learn the basics of Adobe Illustrator, a program perfect for graphic designers to make high quality vector\n";
print "            graphics.\n";
print "        </td>\n";
print "    </tr>\n";
print "    <tr>\n";
print "        <td>Premiere Pro</td>\n";
print "        <td>Learn the basics of Adobe Premiere Pro, a video editing program for making professionally cut videos.</td>\n";
print "    </tr>\n";
print "    <tr>\n";
print "        <td>After Effects</td>\n";
print "        <td>Learn the basics of Adobe After Effects, a video editing program that it also used to polish shots by the\n";
print "            biggest Hollywood VFX studios today.\n";
print "        </td>\n";
print "    </tr>\n";
print "</table>\n";
print "\n";
print "<p>We're currently expanding our class list. Watch this space for future updates!</p>\n";
print "\n";
print "</body>\n";
print "</html>";

?>